softsimon/ngx-bootstrap-multiselect

README.md
src/multiselect-dropdown.ts

Hi there. Thanks for the awesome component. I've fixed a TypeScript error that was making my build complain and updated the README for Angular2 final users.

Fixed TS error and updated README for Angular2 final.

---

src/multiselect-dropdown.ts

I also had to add btn-secondary to the settings.buttonClasses for it to look right.

Bootstrap v4 support

---

package.json

-angular dependency upgraded to ^2.4.0
-devDependencies and peerDependencies fused into dependencies

Project dependencies updated

---

.editorconfig
package.json
src/multiselect-dropdown.html
src/multiselect-dropdown.ts
tslint.json

-Linter added (tslint).
-Editorconfig added.
-Code lintered.

Linter added. Editorconfig added.

---

src/multiselect-dropdown.ts

differs is only used in constructor

Do not create member variable for differs

---

src/multiselect-dropdown.ts

To avoid Angular2 sanitization warnings :
`WARNING: sanitizing unsafe style value cursor: pointer`

Applying Angular's DomSanitizer to style

---

src/multiselect-dropdown.ts

Hi softsimon!
I've added classes for 
li class="dropdown-item"'s representing search and check all/uncheck all buttons, for custom styling

added search and check all/uncheck all classes to li.dropdown-item's

---

.gitignore
package.json
src/multiselect-dropdown.ts
tsconfig.json

Used the ngc compiler to add .metadata.json files making this compatible with AOT. 
Fixes #110

AOT Compatibility

---

README.md
src/multiselect-dropdown.ts

https://github.com/softsimon/angular-2-dropdown-multiselect/issues/112

add dynamicTitle: boolean setting, update Readme

---

src/multiselect-dropdown.ts

add autofocus attribute to search text input to focus inside input element on dropdown open

search input autofocus

---

.npmignore
src/dropdown/dropdown.component.ts
yarn.lock

because of below code in the component:
```
writeValue(value: any): void {
if (value !== undefined && value !== null) {
this.model = value;
} else {
this.model = [];
}
}
```
as well:
guys using the plugins can the type of id is almost `String` type, so `any` should be better here.

change the type of `model` and `parent` from `number[]` to `any[]` 

---

src/dropdown/dropdown.component.html

This change adds ability to add different styles for container/button in opened/closed state.

Toggle "open" class for container

---

src/dropdown/dropdown.component.css
src/dropdown/dropdown.component.html

replaced &nbsp; with css

---

src/dropdown/dropdown.component.ts

Update title when options changed

---

src/dropdown/dropdown.component.ts

Correct default values before ngOnInit

---

src/dropdown/dropdown.component.html
src/dropdown/types.ts

Had a requirement for my project to individually add classes to list items in the dropdown. These minor changes solve this.
I can see this being useful to others.

Add ability to set classes to list items

---

README.md
src/dropdown/dropdown.component.html
src/dropdown/dropdown.component.ts
src/dropdown/search-filter.pipe.ts
src/dropdown/types.ts

Hi, in this PR quite a bit of different stuff so I'll explain below.
First fixes, as mentioned https://github.com/softsimon/angular-2-dropdown-multiselect/pull/227 by default it was showing empty message now it's fixed.
All event handlers have now guarded access to event methods since some applications can run in webworker platform and calls like `e.preventDefault()` would fail.
A bit simplified template of dropdown, removed nested ngIf's.
Usage of filter pipe was moved from template into class to have results in a variable to be able to access it from more than one place.
Added new output `onFilter` which basically is a stream of search field values.
Added new setting `closeOnClickOutside` which by default is `true`. Adds ability to disable auto closing when user clicks outside of …

Fix a bug in filtering + a few improvements

---

src/dropdown/dropdown.component.html

Hi, this tiny fix is solely for those who want to use this component with the webworker platform.
So far there is a [special case](https://github.com/angular/angular/issues/18342) where clicks will not work and so there is a workaround applied here:
It wraps every option's `a` tag in the `div`.
Thats all that is required to workaround the bug.
Thanks

Fix options for WebWorker

---

src/dropdown/dropdown.component.ts

Fix type error

---

src/dropdown/dropdown.component.spec.ts
src/dropdown/dropdown.component.ts

Fix for https://github.com/softsimon/angular-2-dropdown-multiselect/issues/298
Also, base file for developing testing

Lazy load title

---

README.md
src/dropdown/dropdown.component.ts

Instructions for selectAddedValues option

Select all instructions

---

src/dropdown/dropdown.component.ts

https://github.com/softsimon/angular-2-dropdown-multiselect/issues/321

Fix showing selection title if isLazyLoad is true

---

README.md
src/dropdown/dropdown.component.ts
src/dropdown/types.ts

ignore options marked as label when counting selected options

---

src/dropdown/dropdown.component.html

Conforming closer to the bootstrap standard.
Solves
https://github.com/softsimon/angular-2-dropdown-multiselect/issues/267

Added active marking of rows

---

src/dropdown/dropdown.component.css
src/dropdown/dropdown.component.html
src/dropdown/types.ts

It's more touch friendly and should communicate with the end user rather well.
It also allows for the control to support images.
It potentially solves:
https://github.com/softsimon/angular-2-dropdown-multiselect/issues/204

 Added fourth checkedStyle

---

src/dropdown/dropdown.component.ts
src/dropdown/search-filter.pipe.ts
tsconfig.json
yarn.lock

This PR fixes dupe bug in Filter Pipe reported in [this issue](https://github.com/softsimon/angular-2-dropdown-multiselect/issues/337).
Also:
- Refactored Filter Pipe class
- Little refactoring in Dropdown Component to use ES5 arrow functions and removed duplicated import statement
- Added ES7 to typescript config it will not complain about missing `includes`  method on arrays in editors
Thanks

[Fix] Filter Pipe

---

README.md

Added documentation for option 'minSelectionLimit' as it was undocumented.

Documentation of option 'minSelectionLimit'

---

src/demo/src/app/app.component.html
src/demo/src/app/app.component.ts
src/demo/src/app/app.module.ts
src/demo/src/app/data-model.ts
src/demo/src/app/data.service.ts
src/demo/src/app/dummy.component.html
src/demo/src/app/dummy.component.ts
src/demo/src/app/util.ts
src/dropdown/dropdown.component.ts

Summary:
- added a more 'real life' example that use smart / presentation component and load data from service
- changed the `changeDetection` to OnPush
I think it solve other dynamic data loading issues

fix: onPush change detection

---

src/dropdown/types.ts

Remove the whitespace merge conflict which made it into master.

Update types.ts to remove merged conflict

---

src/dropdown/dropdown.component.html

Resolves https://github.com/softsimon/angular-2-dropdown-multiselect/issues/387

csp-fix: unsafe href attribute removal

---

package.json

`$ npm start` start the angular-cli dev server.

build: add npm start script

---

src/dropdown/dropdown.component.html

containerClasses was not working in version 1.7

Added back ngClass directive for containerClasses

---

src/dropdown/dropdown.component.html
src/dropdown/dropdown.component.ts
src/dropdown/dropdown.module.ts
src/dropdown/off-click.directive.ts

Use offClick directive.

---

demo/src/app/dummy.component.html
demo/src/app/dummy.component.ts
src/dropdown/dropdown.component.ts
src/dropdown/search-filter.pipe.ts

Current implementation doesn't allow any customization for filtering search results.
I added the original search filter as default function and allow the user to pass their own function to override it

Add option for custom search function

---

README.md

onChange method has no acceptable parameter $event
Another possible fix would be to change the function

Update README.md - onChange()
