src/multiselect-dropdown.ts
Instead of using the Control from angular2/common which I believe is deprecated in the newest forms API, I just made it use the searchFilterText directly as an NgModel.
Also, in my use case I needed the option id to be a string instead of a number and I figure this makes it more flexible so I included it in my pull request.
I also changed the href attribute in the option links from "#" to "javascript:;" to avoid interfering with hash-style routing.
=> Update to work with RC5 & allow option id to be a string

src/multiselect-dropdown.ts
Fixed Bug # 9 https://github.com/softsimon/angular-2-dropdown-multiselect/issues/9
Fixed two issues below:
1. If the initial selectedOptions array is empty then setSelected gives an error at "this.model.indexOf" as this.model is undefined
2. If the initial selectedOptions array is empty then the initial heading of the drop down is empty
=> Fixed Bug # 9

README.md
Should be `MultiselectDropdown`, not `MultiselectDropdownModule`.
=> Fix MultiselectDropdown typo in README

src/multiselect-dropdown.ts
Do not use strict compare of target nullness, this will prevent an exception when target is 'undefined' instead of null.
=> Fix an unhandled exception when using IE

src/multiselect-dropdown.ts
Fixed missing semicolons, number of version, indentation and tslint warnings like this (Failed to lint: multiselect-dropdown.ts [xx, x]: Exceeds maximum line length of 140)
=> Fix some missing semicolons and tslint warnings.

src/multiselect-dropdown.ts
resolves #28 
I've added a simple `EventEmitter` as an output, and emit event when the drop-down is closed using simple condition in `toggleDropdown()` function
in order to use it just add `(dropdownClosed)="someFunctionInYourClass()"`  to the component HTML selector
=> Added output event when closing the drop-down

.gitignore, package.json, tsconfig.json
@softsimon I have the project set to build the typescript by itself and set the relevant peerDependencies.
Let me know if the version numbers are too high/low for the peer dependencies.  I tried to set them in a way that would be satisfied by any typical installation of an angular project.
I believe all you need to do is update npm with the pre-built js and this should resolve #19
=> Add dev and peer dependencies as well as tsconfig file

src/multiselect-dropdown.ts
- Applying classes to `items`
- Allowing a `params` object to be received
- Exporting `pipe` to be used when extending multiselect class
1. `params?: any;`
We can create an object (or send from backend) like this:
```
optionsObj: IMultiSelectOption[] = [
{
'id': 1,
'name': itemName,
'params': {
'background': '#333'
}
},
{...}
];
```
And we can then apply whatever change we want by extending the Multiselect class. Like this, for example:
`<a *ngIf="!option.isLabel" class="darkMultiselectLink" [style.background-color]="option.params.background" href="javascript:;" role="menuitem" tabindex="-1">`
In an extended class that will override the library's template, for example:
`export class extendedClass extends MultiselectDropdown {
}`
2. `itemClasses?: string;`
Adding a class to the element …
=> Style Customization

src/multiselect-dropdown.ts
Added a new Output() to know when the dropdown is opened and changed the toggleDropdown() method to emit either with the dropdownOpened or dropdownClosed emitter.
=> Added a dropdownOpened Output()

src/multiselect-dropdown.ts
TypeScript 2 currently throws the following compilation errors, if a target project uses this module as an import.
```
node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts(251,12): error TS6133: 'c' is declared but never used.
node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts(259,29): error TS6133: 'fn' is declared but never used.
node_modules/angular-2-dropdown-multiselect/src/multiselect-dropdown.ts(279,15): error TS6133: 'event' is declared but never used.
```
To reproduce, use tsconfig.json with noUnusedParameters flag.
=> Fixing typescript compilation errors

package.json, src/dropdown/dropdown.component.ts, yarn.lock
This PR allows users to update `texts` input property on dropdown and rerender for example a dropdown placeholder text (In my case I wanted to indicate in placeholder that it loads options and then show normal placeholder).
Also this fixes an error being thrown if you do not set `items` input property from the beginning because there were code which was assuming that items is array by default. So I moved that code from `OnInit` to `OnChanges` and guarded items by default to empty array along with updating `parent` property.
NOTE: There's small change in `updateTitle()` method to properly render title when there are no items and no options yet. Previously in that case it was trying to render from `texts.allSelected` property which is wrong so I just moved first if-block below second one so …
=> Allow changing texts input

src/dropdown/dropdown.component.ts
Angulars change detection will not pick up a change inside an array.
Select/deselect all is already working because they overwrite this.model.
However setSelected was not and therefore change detection was not working properly.
=> fixed change detection when selecting a single element

README.md, src/dropdown/dropdown.component.html, src/dropdown/dropdown.component.ts, src/dropdown/dropdown.module.ts, src/dropdown/types.ts
I ran into a performance issue when there are >10000 items in the dropdown it opens quite slow (~2s delay).
I came up with an idea to postpone rendering of items unless user will type something in the filter to reduce amount of items rendered.
This also make sense because users most likely won't scroll through such a big dropdowns but immediately filter them.
I added 2 more properties to settings:
* `searchRenderLimit: number`
0 - By default
If `enableSearch=true` and total amount of items more then `searchRenderLimit` (0 - No limit)
then render items only when user typed more then or equal `searchRenderAfter` characters
* `searchRenderAfter: number`
3 - By default
Also I added 2 more texts:
* `saerchEmptyResult`
Nothing found... - by default
Will be shown when no items are found
* …
=> Add ability to limit rendering of large items

src/dropdown/dropdown.component.ts
I came into an issue where updateTitle() was sometimes being called before ngOnInit.
=> Ensure ngOnInit has executed before calling updateTitle().

src/dropdown/dropdown.component.ts
Seems there is a bug on startup, it will try to set the default text, and that happens before the compare or if it's empty it will crash, this branch fixes that.
=> fixed first run issue when using default text

README.md
It's better to install the package as dependency instead of devDependency (we want in at `build --prod` time) !
=> Switch npm dev-dependency install to dependency

README.md, package.json, src/dropdown/dropdown.component.html, src/dropdown/dropdown.component.ts, src/dropdown/search-filter.pipe.ts, src/dropdown/types.ts
In this PR I put some extra options for even more aggressive optimizations of extremely large sets of options (>5000).
I found that it was not enough of what I did in my [previous PR](https://github.com/softsimon/angular-2-dropdown-multiselect/pull/202) because as I thought the source of lag was only in rendering.
As it turned out after testing - it's not only there but in filtering as well.
Quite a bit of measurements before and after improvement to have some numbers (tested on real mobile devices):
| Lag/delay after every character type | Before Optimizations | After Optimizations |
|------------------------------------------|----------------------|---------------------|
| Avg | ~6s                  | ~500ms              |
| Min | 5s                     | 50ms                     |
| …
=> Deferred rendering further optimizations

src/dropdown/dropdown.component.ts
Hello. 
```ts
import { Modue } from 'rxjs/Rx';
```
This imports the entire RxJS library.
Changing it to
```ts
import { Subject } from 'rxjs/Subject';
import 'rxjs/add/operator/takeUntil';
```
allows to reduce the file size of a build.
After this change, the file size of my final build decreased by **164kb (-68.62%)**.
Before:
After:
=> Don't import entire rxjs/Rx

src/dropdown/dropdown.component.ts, src/dropdown/types.ts
Hi,
This pull request adds the option to have a minimum number of selected items in a list. This feature has been requested in issue #214. This feature works by disallowing unselecting the last x number of items if this options is configured. This can configured in the new option 'minSelectionLimit'. The unselectall button also respects this setting.
=> Configurable option for the minimum number of allowed items selected

src/dropdown/dropdown.component.ts
By default `model` property is undefined and also in `writeValue()` method it is possible that value can be set to something else rather than array (like number or string).
But all across the code the model usage assumes that it is array and so this situation is potentially error prone as in some places there are checks for `undefined` and in some places there aren't (like in `checkAll()` method).
So this PR makes sure that model from the beginning is set to empty array and guards `writeValue()` method to prevent arbitrary values being set.
Also I removed unnecessary checks for undefined since model will be consistent now.
=> Make sure model is always valid array

README.md, src/dropdown/dropdown.component.html, src/dropdown/dropdown.component.ts, src/dropdown/types.ts
Code and documentation for 'searchEmptyResult' configuration is misspelled. This fixes the typo in all places.
=> Correct typo of saerchEmptyResult to searchEmptyResult

README.md
`searchEmptyResult` and `searchNoRenderText` from IMultiSelectTexts were not documented.
=> Adding missing text keys to documentation

src/dropdown/dropdown.component.ts, src/dropdown/types.ts
Select all will currently only select what is loaded and displayed. This change will continue to apply "Check All", including those done during searches, to new data that is loaded in either on scroll or on search.
Applying "Check All" during a search will accumulate that search to a register. Multiple searches with "Check All" will all be stored and applied.
"Uncheck All" during a search will clear that particular search pattern. A search that matches more than one "Check All" will only be cleared when all matching searches have been cleared.
Applying "Check All" with no search criteria clears all individual check all registers and will check everything. A ```checkAllStatus``` boolean stores when this has been set.
Applying "Uncheck All" with no search criteria also clears all search …
=> Lazy load select all

README.md
This is the first set of instructions for lazy loading, including an example Plunker showing how it is used. When ```selectedAddedValues``` is released, I'll be able to update the Plunker to include the added functionality, and I'll also add a section in the ReadMe about the select all functionality as well as other requirements for using it.
=> Instructions for lazy loading

src/dropdown/dropdown.component.ts
Bug fix. If a user checks "Select All" with a search filter applied, with ```isLazyLoad``` set to ```true``` and ```selectAddedValues``` set to ```true```, when they scroll in new lazy load values, those matching values will also check. If they then change the search filter selection such that all selected values are no longer showing, then return to that same search and select "Uncheck All", any value previously checked that is currently not showing will not be unchecked. As the user scrolls in lazy load values, the incoming values that were previously checked remain checked when they should be unchecked. This branch fixes that bug.
=> Deselect all bug

.gitignore, src/dropdown/dropdown.component.html
This is not intuitive when **li** element have cursor: pointer and only **a** element is triggering uncheck/check all function. This way is much better.
I also added .idea folder to .gitignore.
=> Change uncheck/check all trigger element

src/dropdown/dropdown.component.ts
The change event is fired although the value didn't change. This caused some code that was listening for a change in the dropdown to run although it shouldn't have.
=> Only fire model change event if model really changed

src/dropdown/dropdown.component.ts
It looks like it will be good  to check `this.lazyLoadOptions.length` because I see that it can be empty array and in this case we need to use `this.options`
=> this.lazyLoadOptions is an array so it will be true all time

src/demo/src/app/app.component.css, src/dropdown/dropdown.component.html, src/dropdown/dropdown.component.ts
This PR fixes issues with keyboard access (via arrow keys and space selection).
Previously when you were on page with scroll and trying to navigate items via arrow key the whole page was jumping along because events were not prevented - now it's fixed.
Now `Tab` and `Shift + Tab` keyboard strokes also handled same way as arrow up/down keys.
Also demo page was updated to have scrolling to test this kind of interactions.
=> [Fix] Keyboard UX

.prettierrc, src/dropdown/dropdown.component.ts
- Allows `settings` and `texts` inputs to be partial objects.
- It will not mutate internal default settings and texts.
NOTE: I added config for Prettier and reformatted `dropdown.component.ts` file according to the rules specified.
Actual changes are in commit 94d4bd9
=> [Fix] Settings and texts

README.md, src/dropdown/dropdown.component.ts, src/dropdown/types.ts
* Default is false, maintaining existing functionality
* When true, the dropdown title will display selections in the order they were selected
PR for: #366
=> Adds 'maintainSelectionOrderInTitle' setting.

README.md, src/dropdown/dropdown.component.html, src/dropdown/dropdown.component.ts, src/dropdown/types.ts
Needed this today for a country list where they still wanted to see the country in the picker but disable the countries where the selection is not allowed .e.g. region locked
I see this resolves #186 if you want to test it replace your npm line to 
`"angular-2-dropdown-multiselect": "kevcjones/angular-2-dropdown-multiselect#distalt",`
and make sure your imports from `from 'angular-2-dropdown-multiselect/dist';` because obviously i've just pushed the npm dist package to my repo for now.
*using the fontawesome rendering but i think i covered the others, both alt renderers use the -lock icon and the native uses the native disabled look*
``` typescript
this.countryOptions = allCountries.map(c => {
return {id: c.sys.id, name: c.name, disabled: c.blockAccess};
});
```
_Disclaimer - sorry for …
=> Add support to IMultiSelectOption for disabled and the supporting UI/UX to obey it

README.md, src/dropdown/dropdown.component.ts, src/dropdown/types.ts
I would like set this functionality from settings, because in my use case 
- when user select 'Other' options then popup open and user have to set the new value. 
The original behaviour removed the focus from the pop-up input.
=> feat: Allow to set focusBack option in settings

src/dropdown/dropdown.component.ts
on Mac with Chrome 64/65/67 when the user clicked in the checkbox the selection state of the option in changed, but checkbox state remained the old state.
This PR tested on Mac with Chrome 64/65/67 and Firefox 57/58/59
=> fix: checkbox selection state

src/dropdown/dropdown.component.html
Greetings!
My project used Font Awesome v4 and we love this project but it currently doesn't support it. This is because in the newer versions of FA-V4 they replace the element that uses the typical `fa-*` classes with an `svg` instead.
This means if you previously had conditions like `*ngIf` on elements that had these classes they would be eaten up in the process which was leading to bugs like checkmarks staying around even when unselected.
Fairly simple fix. Let me know if you need anything else and how soon we can get this in a minor version bump!
Thanks
=> Support fontawesome 4 usage

src/dropdown/dropdown.component.html, src/dropdown/dropdown.component.ts
adding `isLabel` to an option throws an error. This is because the `isCheckboxDisabled` method looks for `disabled`'s value on an option item of undefined as there is never an option sent as the param inside the template. Simply adding the option as a param inside the template fixes this, but I adapted the `isCheckboxDisabled` method to make it future proof too.
=> fix(isCheckboxDisabled): isLabel option breaks disabled check

demo/src/app/dummy.component.html, demo/src/app/dummy.component.ts, src/dropdown/dropdown.component.ts
This was ennoying us for a while...
When you filter for items and click `check all`, all filtered items got fixed (and no others). But when clicking  `uncheck all`, also all unfiltered items, aka all items, got unchecked. This PR solves this inconsistency. 
PS: there should really be a possibility to write unit tests...
=>  Only uncheck filtered items

src/package.json
When installing the angular-2-dropdown-multiselect there are warnings about the peer dependencies.
With this update of the peer dependencies versions there shouldn't be a warning.
=> Update peer dependencies versions

demo/e2e/tsconfig.e2e.json, demo/src/tsconfig.app.json, demo/src/tsconfig.spec.json, src/dropdown/dropdown.component.html, src/dropdown/off-click.directive.ts, src/dropdown/types.ts
This PR fixes the following compile errors that occur if you try to `ng build --aot` an application with `fullTemplateTypeCheck: true`:
`ERROR in src/dropdown/dropdown.component.html(62,15): : Operator '==' cannot be applied to types '"checkboxes" | "glyphicon" | "fontawesome"' and '"visual"'.
src/dropdown/dropdown.component.html(7,58): : Operator '==' cannot be applied to types '"checkboxes" | "glyphicon" | "fontawesome"' and '"visual"'.
src/dropdown/dropdown.component.html(1,1): : Directive OffClickDirective, Property 'onDocumentClick' is private and only accessible within class 'OffClickDirective'.
src/dropdown/dropdown.component.html(1,1): : Directive OffClickDirective, Property 'onDocumentTouch' is private and only accessible within class 'OffClickDirective'. …
=> Fix AOT fullTemplateTypeCheck compile errors

README.md
Adding Stackblitz link, since I have not been able to open a single Plunker file in several months.
=> Update Plunker link to Stackblitz

src/lib/ngx-bootstrap-multiselect.component.html
Steps to reproduce:
1. Click select
2. Search for an option that not exist
3. Input is gone and unable to remove search query
Stackblitz: https://stackblitz.com/edit/angular-rhuxn7
Example: https://share.getcloudapp.com/jkuYlL9d
Version used: 2.1 (latest)
=> Show search-container when filter has a value
